"""One-time `/setup` claim flow.

The Phase-1 no-email recipe. The trust-boundary model:

  - The secret is **generated by the deployer's local machine**
    (`openssl rand -hex 32`) immediately before `sam deploy` and
    passed as a CFN `NoEcho` parameter `BootstrapSetupKey`.
  - SAM bakes it as a Lambda env var `IAM_JIT_BOOTSTRAP_SETUP_KEY`.
  - CFN outputs include ONLY the bare URL `https://…/setup` — never
    the secret. Any account principal with
    `cloudformation:DescribeStacks` access sees no useful information.
  - The deployer remembers the secret (terminal history, password
    manager, .env file) and types it into the `/setup` form when
    they visit the URL the first time.

The flow:

  1. Deployer runs `openssl rand -hex 32` and saves the output.
  2. `sam deploy --parameter-overrides BootstrapSetupKey=<that value> …`
  3. CFN output `BootstrapClaimUrl` is just `https://<func-url>/setup`.
  4. Deployer opens the URL, enters their email and the secret.
  5. Server: constant-time-compares the submitted key to the env var,
     matches the email against `AdminBootstrapEmail`, confirms the
     bootstrap admin user record exists AND hasn't been claimed yet
     (a `[claimed at ...]` marker is appended to `user.notes` on
     first success — single-use guarantee).
  6. Success → session cookie for the bootstrap admin + redirect to
     `/admin/network`. The setup key is then unusable forever for
     that user.

Why this is tighter than putting the URL-with-secret in CFN outputs:
the secret never lives in any AWS resource a wide IAM-admin role
can read. The narrowest reader is someone with
`lambda:GetFunctionConfiguration` on the iam-jit function — which
is a much smaller set than "anyone with CFN-stack-read". For deeper
hardening (production), store the key in Secrets Manager with a
resource policy and read it at runtime — v2 idea.

Brute-force defense: per-IP rate limit on `/setup` (kind=`setup`)
plus single-use after first success. 32 hex bytes = 2^256 space; a
realistic attacker can't beat the rate limit before someone notices.
"""

from __future__ import annotations

import dataclasses
import datetime as _dt
import hmac
import logging
from dataclasses import dataclass
from typing import Any

from .users_store import User, UserStore, UserNotFound


logger = logging.getLogger("iam_jit.bootstrap_claim")


_CLAIMED_MARKER = "[claimed at "


@dataclass(frozen=True)
class ClaimDecision:
    success: bool
    user_id: str | None
    reason: str
    """One of: 'success', 'no_admin_configured', 'no_secret_configured',
    'invalid_key', 'email_mismatch', 'bootstrap_user_missing',
    'already_claimed', 'store_write_failed'."""


def _now_iso_z() -> str:
    return _dt.datetime.now(_dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _has_been_claimed(user: User) -> bool:
    if not user.notes:
        return False
    return _CLAIMED_MARKER in user.notes


def evaluate_and_claim(
    *,
    submitted_email: str,
    submitted_key: str,
    admin_bootstrap_email: str,
    bootstrap_setup_key: str,
    user_store: UserStore,
) -> ClaimDecision:
    """Pure-input function that decides + (on success) writes the
    claim marker to the bootstrap admin's user record.

    `bootstrap_setup_key` is the value of the Lambda env var
    `IAM_JIT_BOOTSTRAP_SETUP_KEY` (deployer-supplied at `sam deploy`
    time, NOT the same as `MagicLinkSecret`). When empty, the
    `/setup` endpoint is disabled — the operator must use email or
    `IAM_JIT_DEV_INSECURE_SECRET=1` instead.

    The caller (the FastAPI route) is responsible for setting the
    session cookie + the HTTP redirect on success — keeps this
    module free of FastAPI imports for testability.
    """
    expected_email = (admin_bootstrap_email or "").strip().lower()
    if not expected_email:
        return ClaimDecision(
            success=False, user_id=None, reason="no_admin_configured"
        )
    if not bootstrap_setup_key:
        return ClaimDecision(
            success=False, user_id=None, reason="no_secret_configured"
        )

    if not hmac.compare_digest(
        submitted_key or "", bootstrap_setup_key
    ):
        return ClaimDecision(
            success=False, user_id=None, reason="invalid_key"
        )

    submitted_normalized = (submitted_email or "").strip().lower()
    if submitted_normalized != expected_email:
        return ClaimDecision(
            success=False, user_id=None, reason="email_mismatch"
        )

    user_id = f"email:{expected_email}"
    try:
        user = user_store.get(user_id)
    except UserNotFound:
        return ClaimDecision(
            success=False, user_id=user_id, reason="bootstrap_user_missing"
        )
    except Exception:
        logger.exception("claim: user_store.get failed")
        return ClaimDecision(
            success=False, user_id=user_id, reason="bootstrap_user_missing"
        )

    if _has_been_claimed(user):
        return ClaimDecision(
            success=False, user_id=user_id, reason="already_claimed"
        )

    marker = f" {_CLAIMED_MARKER}{_now_iso_z()}]"
    updated = dataclasses.replace(
        user, notes=((user.notes or "") + marker).strip()
    )
    try:
        user_store.put(updated)
    except Exception:
        logger.exception("claim: user_store.put failed")
        return ClaimDecision(
            success=False, user_id=user_id, reason="store_write_failed"
        )

    logger.warning(
        "bootstrap claim consumed by %s — subsequent /setup POSTs will "
        "return 200 with an `already_claimed` flash in setup_claim.html, "
        "advising the user to sign in via /login instead",
        user_id,
    )
    return ClaimDecision(success=True, user_id=user_id, reason="success")


def claim_url(*, base_url: str) -> str:
    """The bare URL we expose in CFN outputs — NO secret, NO email.
    The deployer types both into the form themselves so the
    sensitive material stays out of CFN."""
    return f"{base_url.rstrip('/')}/setup"
