"""Fetch all AWS-scope managed policies + score them locally.

Builds a snapshot of every IAM policy in the canonical AWS-curated set
(~1,400 policies as of 2026-05). Each policy is scored through our
deterministic engine and the result is written to one of:

  - tests/calibration_corpus/aws_managed/<name>.yaml   (one file per
    policy, test-suite-loadable)

  - /tmp/aws-managed-policies.json                      (cached raw
    data, for re-runs without hitting the IAM API again)

The corpus files are regression-protection: each pins
`score_min`/`score_max` around the current deterministic verdict with
±1 tolerance, so the test suite catches the day someone refactors the
scorer and accidentally moves AdministratorAccess from 10 to 5.

The AWS-managed policies are not what the IAM-risk-score scorer was
hand-calibrated against, so this run will surface real outliers — cases
where AWS's official policy guidance and our scorer disagree by a lot.
Those are valuable calibration-target findings.

Run with:
    AWS_PROFILE=iam-jit .venv/bin/python scripts/fetch-aws-managed-policies.py

Re-run with --no-fetch to skip the AWS API hit and use the cached JSON.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
from typing import Any

import boto3
import yaml

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "src"))
from iam_jit.review import analyze_policy  # noqa: E402


CACHE_PATH = pathlib.Path("/tmp/aws-managed-policies.json")
CORPUS_DIR = (
    pathlib.Path(__file__).resolve().parent.parent
    / "tests"
    / "calibration_corpus"
    / "aws_managed"
)


def fetch_all_policies() -> list[dict[str, Any]]:
    """List every AWS-scope managed policy and pull its default version doc."""
    iam = boto3.client("iam")
    paginator = iam.get_paginator("list_policies")
    out: list[dict[str, Any]] = []
    for page in paginator.paginate(Scope="AWS"):
        for p in page["Policies"]:
            out.append(p)
    # For each policy, fetch the default-version document
    enriched: list[dict[str, Any]] = []
    for i, p in enumerate(out, 1):
        if i % 50 == 0:
            print(f"  ...fetched {i}/{len(out)}")
        version = iam.get_policy_version(
            PolicyArn=p["Arn"],
            VersionId=p["DefaultVersionId"],
        )["PolicyVersion"]["Document"]
        enriched.append({
            "PolicyName": p["PolicyName"],
            "Arn": p["Arn"],
            "Description": p.get("Description") or "",
            "PolicyDocument": version,
        })
    return enriched


def _safe_filename(name: str) -> str:
    """Turn a PolicyName into a filename-safe slug."""
    s = re.sub(r"[^A-Za-z0-9_-]", "_", name)
    return s[:80]  # cap length for sanity


def _request_for_scoring() -> dict[str, Any]:
    """Use read-write + 1h as the canonical evaluation context."""
    return {
        "spec": {
            "access_type": "read-write",
            "duration": {"duration_hours": 1},
            "resource_constraints": [],
        }
    }


def score_policy_doc(doc: dict[str, Any]) -> tuple[int, list[str]]:
    analysis = analyze_policy(doc, _request_for_scoring())
    return analysis.risk_score, list(analysis.risk_factors)


def generate_yamls(policies: list[dict[str, Any]]) -> dict[str, Any]:
    """Score each policy + write a corpus YAML per policy. Returns summary stats."""
    CORPUS_DIR.mkdir(parents=True, exist_ok=True)
    distribution: dict[int, int] = {i: 0 for i in range(1, 11)}
    written = 0
    skipped = 0

    for p in policies:
        name = p["PolicyName"]
        arn = p["Arn"]
        doc = p["PolicyDocument"]
        desc = p["Description"]

        try:
            score, factors = score_policy_doc(doc)
        except Exception as e:
            print(f"  SKIP {name}: scoring failed: {e}")
            skipped += 1
            continue

        distribution[score] = distribution.get(score, 0) + 1

        # Tolerance band: ±1 around the current score, clipped to [1,10].
        score_min = max(1, score - 1)
        score_max = min(10, score + 1)

        # Build a comment line containing the AWS-stated description so a
        # reviewer reading the YAML knows what AWS intends this policy
        # for. Sanitize newlines.
        desc_clean = " ".join((desc or "").split())[:200]

        yaml_data = {
            "name": f"aws-managed-{name}",
            "description": (
                f"AWS-managed policy snapshot. ARN: {arn}\n"
                f"AWS description: {desc_clean or '(none)'}\n"
                f"Generated by scripts/fetch-aws-managed-policies.py — "
                f"regression-protects the deterministic score against "
                f"future rule refactors. Current det_score={score}; "
                f"tolerance ±1 reflects small calibration deltas."
            ),
            "policy": doc,
            "request": {
                "spec": {
                    "access_type": "read-write",
                    "duration": {"duration_hours": 1},
                }
            },
            "expected": {
                "score_min": score_min,
                "score_max": score_max,
            },
        }

        slug = _safe_filename(name)
        out_path = CORPUS_DIR / f"{slug}.yaml"
        with out_path.open("w", encoding="utf-8") as f:
            yaml.safe_dump(
                yaml_data, f, sort_keys=False, default_flow_style=False, width=120
            )
        written += 1

    return {
        "written": written,
        "skipped": skipped,
        "distribution": distribution,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--no-fetch", action="store_true",
        help="Use cached /tmp/aws-managed-policies.json instead of hitting IAM API",
    )
    parser.add_argument(
        "--limit", type=int, default=None,
        help="Only process the first N policies (for testing)",
    )
    args = parser.parse_args()

    if args.no_fetch and CACHE_PATH.exists():
        print(f"Loading cached policies from {CACHE_PATH}")
        policies = json.loads(CACHE_PATH.read_text())
    else:
        print("Fetching AWS-managed policies via IAM API...")
        policies = fetch_all_policies()
        CACHE_PATH.write_text(json.dumps(policies, default=str))
        print(f"Cached {len(policies)} policies to {CACHE_PATH}")

    if args.limit:
        policies = policies[: args.limit]
        print(f"Limiting to first {len(policies)} policies for this run")

    print(f"Scoring + generating YAMLs for {len(policies)} policies...")
    stats = generate_yamls(policies)

    print()
    print(f"Wrote {stats['written']} YAML files to {CORPUS_DIR}")
    print(f"Skipped {stats['skipped']}")
    print()
    print("Score distribution (1=safe, 10=admin-equivalent):")
    for s in range(1, 11):
        bar = "#" * (stats["distribution"].get(s, 0) // 5)
        print(f"  {s}: {stats['distribution'].get(s, 0):4d}  {bar}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
