"""Bouncer process discovery + env-var wiring for `iam-jit posture`.

Detects:
  * Whether each of ibounce / kbounce / dbounce / gbounce is running
    (cheap loopback TCP probe to the bouncer's default management
    port; honors per-bouncer env-var overrides).
  * Whether the operator's env vars point at THAT bouncer (or at a
    different port — the "misconfig" case per
    [[ibounce-honest-positioning]]).
  * For ibounce only: the live active mode + profile name (read
    in-process via the existing helpers when this module is imported
    inside the ibounce mcp/cli process; otherwise reports
    "unknown — bouncer not introspectable from this process").

Each bouncer's default port + env-var name comes from the bouncer's
own CLI/run-command spec:

  * ibounce:  --port 8767 (loopback), env IAM_JIT_BOUNCER_PROFILE
              (env points at 127.0.0.1:8767 via AWS_ENDPOINT_URL)
  * kbounce:  --port 8766, KUBECONFIG points at a kbounce-generated
              file (file header contains a comment marker we scan for)
  * dbounce:  --port 5433 (wire), --mgmt-port 8768. ``posture`` probes
              the mgmt port for /healthz.
  * gbounce:  --port 8080 (wire), --mgmt-port 8769. ``posture`` probes
              the mgmt port (since /healthz lives there per
              [[ibounce-honest-positioning]]).

Process discovery is intentionally NETWORK-PROBE-BASED rather than
``ps``-based — works in containers, doesn't need /proc, doesn't race
with start-up. Cost is one TCP-connect per bouncer per call (< 5ms
total on loopback).
"""

from __future__ import annotations

import json
import os
import pathlib
import re
import socket
from contextlib import closing
from typing import Any

# ---- Default ports + env-var names per bouncer --------------------------
# Source of truth: each bouncer's `run` CLI flag default. If those
# change, update here. Tests pin the defaults (`test_posture_defaults`).

IBOUNCE_DEFAULT_PORT = 8767
IBOUNCE_AWS_ENDPOINT_ENV = "AWS_ENDPOINT_URL"

KBOUNCE_DEFAULT_PORT = 8766
KBOUNCE_ENV_KUBECONFIG = "KUBECONFIG"
# Marker we expect to see at the top of kbounce-generated kubeconfigs.
# kbounce writes ``# Generated by kbounce`` as the first comment.
KBOUNCE_KUBECONFIG_MARKER = "# Generated by kbounce"

DBOUNCE_DEFAULT_WIRE_PORT = 5433
DBOUNCE_DEFAULT_MGMT_PORT = 8768
DBOUNCE_ENV_PGHOST = "PGHOST"
DBOUNCE_ENV_PGPORT = "PGPORT"

GBOUNCE_DEFAULT_WIRE_PORT = 8080
GBOUNCE_DEFAULT_MGMT_PORT = 8769
GBOUNCE_ENV_HTTP_PROXY = "HTTP_PROXY"
GBOUNCE_ENV_HTTPS_PROXY = "HTTPS_PROXY"

# ---- autopilot.status.json port hints -----------------------------------
#
# #514 — canary-port deployments: when the operator ran a bouncer on a
# non-default port (e.g. ``ibounce run --port 9876``), the default-port
# probe misses it. ``autopilot.status.json`` records the actual port each
# bouncer was started on. Read that file FIRST and augment the probe set.
#
# Same pattern as #617 MED-2 in cli_uninstall.py (``_read_autopilot_ports``
# there). Kept as a separate, lighter copy here because:
#   * cli_uninstall is not importable in all environments (heavy deps).
#   * posture needs only the port-hint slice, not the full inventory.
#
# Honor ``IAM_JIT_DATA_DIR`` for fixture isolation in tests (same env var
# the rest of iam-jit uses for the data-directory root).

_IAM_JIT_DATA_DIR_ENV = "IAM_JIT_DATA_DIR"
_AUTOPILOT_STATUS_FILENAME = "autopilot.status.json"
# Written by serve() at bind time; removed on clean shutdown.
_IBOUNCE_RUNNING_FILENAME = "ibounce-running.json"


def _autopilot_data_dir() -> pathlib.Path:
    """Return the iam-jit data directory, honoring ``IAM_JIT_DATA_DIR``."""
    raw = os.environ.get(_IAM_JIT_DATA_DIR_ENV, "").strip()
    if raw:
        return pathlib.Path(raw).expanduser()
    return pathlib.Path.home() / ".iam-jit"


def _read_autopilot_port_hints() -> dict[str, list[int]]:
    """Return per-bouncer port hints from ``autopilot.status.json``.

    #514 fix: Reads ``~/.iam-jit/autopilot.status.json`` (or the path
    under ``IAM_JIT_DATA_DIR``) and extracts the ``port`` field from each
    bouncer block that autopilot recorded as running. These ports are
    ADDITIVE — they supplement the default-port probe so canary-port
    deployments are discovered without breaking the no-autopilot fallback.

    Returns ``{bouncer_kind: [port, ...]}`` — empty dict when the file
    doesn't exist, can't be parsed, or contains no useful port data.
    Per [[ibounce-honest-positioning]]: parse failure is non-fatal and
    silently falls back to default-port probing.
    """
    status_path = _autopilot_data_dir() / _AUTOPILOT_STATUS_FILENAME
    if not status_path.exists():
        return {}
    try:
        raw = status_path.read_text(encoding="utf-8", errors="replace")
        data = json.loads(raw)
    except (OSError, json.JSONDecodeError):
        return {}

    bouncers_block = data.get("bouncers")
    if not isinstance(bouncers_block, dict):
        return {}

    result: dict[str, list[int]] = {}
    for name, block in bouncers_block.items():
        if not isinstance(block, dict):
            continue
        # Skip bouncers autopilot explicitly marks as not running.
        # Per [[safety-mode-lean-permissive]]: treat missing ``running``
        # as "unknown — still worth checking".
        if block.get("running") is False:
            continue
        port_val = block.get("port")
        if port_val is None:
            continue
        try:
            port = int(port_val)
        except (ValueError, TypeError):
            continue
        if port <= 0 or port > 65535:
            continue
        result.setdefault(name, []).append(port)
    return result


# ---- Helpers ------------------------------------------------------------


def _loopback_port_open(port: int, host: str = "127.0.0.1", timeout: float = 0.25) -> bool:
    """Cheap loopback TCP probe. Returns True iff something is
    accepting connections at ``host:port`` within ``timeout`` seconds.

    Never raises — connection failures (refused / unreachable /
    timeout / DNS) all return False. Caller decides what to make of
    a False (could be "not running" OR could be "running on a
    different port").
    """
    if port <= 0 or port > 65535:
        return False
    with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as sock:
        sock.settimeout(timeout)
        try:
            sock.connect((host, port))
        except OSError:
            return False
        return True


_LOOPBACK_HOSTS = {"127.0.0.1", "localhost", "::1", "[::1]"}


def _read_ibounce_running_port() -> int | None:
    """Return the port from ``ibounce-running.json`` if present and live.

    This file is written by ``serve()`` immediately after binding + deleted
    in the ``finally`` block, so its presence means ibounce is (or was very
    recently) running on that port.  TCP-probe the port before returning it —
    if ibounce crashed without cleanup the stale file would give a wrong
    answer.  Returns ``None`` on any parse / probe failure.
    """
    hint_path = _autopilot_data_dir() / _IBOUNCE_RUNNING_FILENAME
    if not hint_path.exists():
        return None
    port: int | None = None
    try:
        data = json.loads(hint_path.read_text(encoding="utf-8", errors="replace"))
        raw_port = int(data.get("port", 0))
        if 0 < raw_port <= 65535:
            port = raw_port
    except (OSError, json.JSONDecodeError, ValueError, TypeError):  # noqa: SD-1 — parse failure is the expected "no valid hint" path; caller checks port is None and falls back to autopilot / TCP probe
        pass
    if port is None:
        return None
    # Validate the hint is still live before trusting it.
    if not _loopback_port_open(port):
        return None
    return port


def _parse_url_for_loopback_port(url: str) -> int | None:
    """If ``url`` is a loopback http(s) URL, return its port. Else None.

    Used for AWS_ENDPOINT_URL / HTTP_PROXY decoding. Doesn't validate
    the scheme strictly — anything of shape
    ``[scheme://]host[:port][/...]`` works.
    """
    if not url:
        return None
    s = url.strip()
    # Strip optional scheme.
    if "://" in s:
        s = s.split("://", 1)[1]
    # Strip optional path.
    s = s.split("/", 1)[0]
    # Strip credentials prefix (user:pass@host).
    if "@" in s:
        s = s.split("@", 1)[1]
    # Split host:port — handle IPv6 [::1]:port.
    if s.startswith("["):
        # IPv6 form.
        if "]" not in s:
            return None
        host, _, rest = s.partition("]")
        host = host + "]"
        if rest.startswith(":"):
            port_str = rest[1:]
        else:
            port_str = ""
    else:
        host, _, port_str = s.partition(":")
    if host not in _LOOPBACK_HOSTS:
        return None
    if not port_str:
        # No explicit port; loopback URLs without a port aren't
        # meaningful for bouncer detection (bouncers always bind to
        # an explicit port).
        return None
    try:
        return int(port_str)
    except ValueError:
        return None


def _kubeconfig_is_kbounce(path: str) -> bool:
    """Read the first ~1KB of a kubeconfig + check for the kbounce
    marker. Tolerant of missing file / permission errors / binary
    content — all return False."""
    if not path:
        return False
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            head = fh.read(1024)
    except (OSError, UnicodeDecodeError):
        return False
    return KBOUNCE_KUBECONFIG_MARKER in head


# ---- Per-bouncer detection ---------------------------------------------


def detect_ibounce() -> dict[str, Any]:
    """Detect ibounce's posture.

    Returns a dict matching the §A42 spec's per-bouncer block:
      {
        "running": bool,
        "port": int,
        "default_port": int,
        "mode": str | "unknown",
        "active_profile": str | "unknown",
        "env_var_pointing_here": str | None,
        "misconfig": str | None,
      }

    Live mode / profile read is attempted via the in-process
    ``resolve_active_mode`` / ``resolve_active_profile`` helpers when
    they're importable (i.e. when posture is invoked inside the
    iam-jit Python venv). Failure to import is non-fatal — fields
    fall back to "unknown".

    #514 — canary-port support: when ``autopilot.status.json`` records
    ibounce running on a non-default port we probe THAT port first so
    the bouncer is not missed. Default-port probe always runs as a
    fallback (handles the no-autopilot case).
    """
    # Highest-priority port hint: ibounce-running.json written by
    # serve() immediately after binding. Supersedes autopilot + default
    # so `ibounce run --port 9876` (without autopilot / AWS_ENDPOINT_URL)
    # is reported correctly in `ibounce posture`.  The helper TCP-probes
    # the hinted port before returning it so a stale file never produces
    # a false "RUNNING" report.
    running_port = _read_ibounce_running_port()
    if running_port is not None:
        block: dict[str, Any] = {
            "running": True,
            "port": running_port,
            "default_port": IBOUNCE_DEFAULT_PORT,
        }
        # Skip the autopilot + TCP probe chain — we already verified
        # the port is live.  Fall through to the in-process introspection
        # + env-var checks below.
    else:
        # #514: gather any autopilot-hinted ports for ibounce.  Probe hints
        # FIRST (they are the authoritative declaration from the daemon that
        # started the bouncer), then fall back to the default if no hint is
        # live.  dict.fromkeys preserves insertion order + deduplicates so if
        # autopilot recorded the default port we don't probe it twice.
        ap_hints = _read_autopilot_port_hints()
        ibounce_ports: list[int] = list(
            dict.fromkeys(ap_hints.get("ibounce", []) + [IBOUNCE_DEFAULT_PORT])
        )

        # Probe each candidate port; use the first live one.
        port = IBOUNCE_DEFAULT_PORT
        running = False
        for _p in ibounce_ports:
            if _loopback_port_open(_p):
                port = _p
                running = True
                break
        if not running:
            # Keep the default so block["port"] is always meaningful.
            port = IBOUNCE_DEFAULT_PORT

        block = {
            "running": running,
            "port": port,
            "default_port": IBOUNCE_DEFAULT_PORT,
        }

    # Unpack for the rest of this function which references `running` and
    # `port` directly (both branches set `block`, so this is always safe).
    running = block["running"]
    port = block["port"]

    # In-process introspection: import the same helpers the MCP tools
    # use. Cheap (no IO beyond reading env vars + YAML).
    mode_info: dict[str, Any] | None = None
    profile_info: dict[str, Any] | None = None
    try:
        from ..bouncer.proxy import resolve_active_mode

        mode_info = resolve_active_mode()
    except Exception:
        mode_info = None
    try:
        from ..bouncer.profiles import load_profiles, resolve_active_profile

        profile = resolve_active_profile(
            cli_flag=None, profiles=load_profiles()
        )
        profile_info = {
            "name": profile.name,
            "deny_keyword_count": len(profile.deny_keywords),
            "deny_verb_count": len(profile.deny_verbs),
            "only_account_id_count": len(profile.only_account_ids),
            "allow_rule_count": len(profile.allow_rules),
            "source": profile.source,
        }
    except Exception:
        profile_info = None

    block["mode"] = mode_info["mode"] if mode_info else "unknown"
    block["mode_source"] = (
        mode_info["source"] if mode_info else "unknown"
    )
    if profile_info:
        block["active_profile"] = profile_info["name"]
        block["profile_summary"] = profile_info
    else:
        block["active_profile"] = "unknown"

    # #424 / §A63 — disk-pressure surface. In-process read works ONLY
    # when posture is invoked from inside a running ibounce serve()
    # process (the disk-pressure state is in-process; not persisted).
    # Otherwise we probe /healthz over HTTP if the bouncer is reachable
    # (the audit_log block is always present on /healthz per §A63).
    # On failure to read either, we surface "unknown" rather than
    # absent — per [[ibounce-honest-positioning]] missing data is
    # named, not hidden.
    disk_pressure: dict[str, Any] | None = None
    try:
        from ..bouncer.proxy import active_disk_pressure_state
        from ..bouncer.audit_export import healthz_audit_log_block
        _dp = active_disk_pressure_state()
        if _dp is not None:
            disk_pressure = healthz_audit_log_block(_dp)
    except Exception:
        disk_pressure = None
    if disk_pressure is None and running:
        # Out-of-process probe via /healthz. Short timeout — posture
        # is interactive; we don't want to hang the operator if the
        # bouncer is unresponsive.
        try:
            import json
            import urllib.error
            import urllib.request
            req = urllib.request.Request(
                f"http://127.0.0.1:{port}/healthz",
                method="GET",
            )
            with urllib.request.urlopen(req, timeout=1.0) as resp:
                payload = json.loads(resp.read().decode("utf-8"))
                disk_pressure = payload.get("audit_log")
        except (urllib.error.URLError, OSError, ValueError, TimeoutError):
            disk_pressure = None
    if disk_pressure is not None:
        block["disk_pressure"] = disk_pressure
        # Surface a single-line operator-facing recommendation when
        # the bouncer is approaching critical or already at it.
        _status = disk_pressure.get("status")
        _used = disk_pressure.get("used_pct")
        _mode = disk_pressure.get("disk_pressure_mode")
        if _status in ("critical", "emergency"):
            block["disk_pressure_recommendation"] = (
                f"disk pressure {_status} at {_used}% used; "
                f"mode={_mode}. Clear space in the audit-log "
                "directory OR switch to rotate-aggressively / "
                "archive-and-purge to recover automatically."
            )
        elif _status == "degraded":
            block["disk_pressure_recommendation"] = (
                f"disk approaching threshold at {_used}% used. "
                "Consider archiving older rotated logs OR raising "
                "--disk-pressure-warn-pct if the threshold is set "
                "too tight for your retention window."
            )
        else:
            block["disk_pressure_recommendation"] = None
    else:
        block["disk_pressure"] = None
        block["disk_pressure_recommendation"] = None

    # #499 / §A76b — Phase H anomaly-detection surface. Same in-process
    # / out-of-process probe pattern as disk_pressure above. Always
    # present (None when the hook is NOT installed) so agents reading
    # posture can branch on a single field instead of a missing key.
    # Per [[ibounce-honest-positioning]] the absence of this marker is
    # itself the operator-observable signal that the bouncer is NOT
    # scoring requests.
    anomaly_detection: dict[str, Any] | None = None
    try:
        from ..bouncer.proxy import active_anomaly_detection_marker
        anomaly_detection = active_anomaly_detection_marker()
    except Exception:
        anomaly_detection = None
    if anomaly_detection is None and running:
        try:
            import json
            import urllib.error
            import urllib.request
            req = urllib.request.Request(
                f"http://127.0.0.1:{port}/healthz",
                method="GET",
            )
            with urllib.request.urlopen(req, timeout=1.0) as resp:
                payload = json.loads(resp.read().decode("utf-8"))
                anomaly_detection = payload.get("anomaly_detection")
        except (urllib.error.URLError, OSError, ValueError, TimeoutError):
            anomaly_detection = None
    block["anomaly_detection"] = anomaly_detection

    # #711 — audit-export silent-degradation guard. Read audit_warning
    # from /healthz (non-null when decisions_count > 0 AND audit_export
    # is not configured). Always present (None = healthy) so posture
    # consumers can branch on a single field.
    audit_warning: str | None = None
    if running:
        try:
            import json as _json
            import urllib.error as _ue
            import urllib.request as _ur
            _req = _ur.Request(
                f"http://127.0.0.1:{port}/healthz",
                method="GET",
            )
            with _ur.urlopen(_req, timeout=1.0) as _resp:
                _payload = _json.loads(_resp.read().decode("utf-8"))
                audit_warning = _payload.get("audit_warning")
        except (_ue.URLError, OSError, ValueError, TimeoutError):
            audit_warning = None
    block["audit_warning"] = audit_warning

    # Env-var wiring + misconfig check.
    endpoint = os.environ.get(IBOUNCE_AWS_ENDPOINT_ENV, "").strip()
    endpoint_port = _parse_url_for_loopback_port(endpoint)
    block["env_var_pointing_here"] = None
    block["misconfig"] = None
    if endpoint:
        if endpoint_port is None:
            # Env points elsewhere (not loopback) — not a misconfig
            # for ibounce, just "operator pointing AWS SDK at a
            # different endpoint".
            block["env_var_pointing_here"] = None
            block["env_var_set_elsewhere"] = (
                f"{IBOUNCE_AWS_ENDPOINT_ENV}={endpoint} "
                "(not loopback)"
            )
        elif endpoint_port == port:
            if running:
                block["env_var_pointing_here"] = (
                    f"{IBOUNCE_AWS_ENDPOINT_ENV}={endpoint}"
                )
            else:
                block["misconfig"] = (
                    f"{IBOUNCE_AWS_ENDPOINT_ENV}={endpoint} but no "
                    "bouncer listening on that port"
                )
        else:
            # Endpoint is loopback but a DIFFERENT port.
            if _loopback_port_open(endpoint_port):
                # Something IS running there — operator probably has
                # ibounce on a non-default port. Not a misconfig.
                block["env_var_pointing_here"] = (
                    f"{IBOUNCE_AWS_ENDPOINT_ENV}={endpoint} "
                    f"(non-default port {endpoint_port})"
                )
                block["running"] = True
                block["port"] = endpoint_port
            else:
                block["misconfig"] = (
                    f"{IBOUNCE_AWS_ENDPOINT_ENV}={endpoint} but no "
                    "bouncer listening on that port"
                )
    return block


def detect_kbounce() -> dict[str, Any]:
    """Detect kbounce's posture. Returns the same shape as
    ``detect_ibounce`` minus the in-process mode/profile (which we
    can't read from a different Python process — Go binary).

    #514 — canary-port support: autopilot-hinted ports are probed
    alongside the default so non-default kbounce deployments are found.
    """
    ap_hints = _read_autopilot_port_hints()
    kbounce_ports: list[int] = list(
        dict.fromkeys(ap_hints.get("kbounce", []) + [KBOUNCE_DEFAULT_PORT])
    )
    port = KBOUNCE_DEFAULT_PORT
    running = False
    for _p in kbounce_ports:
        if _loopback_port_open(_p):
            port = _p
            running = True
            break
    block: dict[str, Any] = {
        "running": running,
        "port": port,
        "default_port": KBOUNCE_DEFAULT_PORT,
        "mode": "unknown",  # Go binary; would need /healthz parse to know
        "active_profile": "unknown",
    }
    kubecfg = os.environ.get(KBOUNCE_ENV_KUBECONFIG, "").strip()
    block["env_var_pointing_here"] = None
    block["misconfig"] = None
    if kubecfg:
        if _kubeconfig_is_kbounce(kubecfg):
            block["env_var_pointing_here"] = (
                f"{KBOUNCE_ENV_KUBECONFIG}={kubecfg} (kbounce-generated)"
            )
            if not running:
                block["misconfig"] = (
                    f"{KBOUNCE_ENV_KUBECONFIG} points at a kbounce-"
                    "generated kubeconfig but kbounce isn't running"
                )
        else:
            block["env_var_set_elsewhere"] = (
                f"{KBOUNCE_ENV_KUBECONFIG}={kubecfg} "
                "(not a kbounce kubeconfig)"
            )
    return block


def detect_dbounce() -> dict[str, Any]:
    """Detect dbounce's posture via PGHOST + PGPORT env vars + a
    loopback probe to the management port.

    #514 — canary-port support: autopilot-hinted ports are probed
    alongside the default so non-default dbounce wire/mgmt deployments
    are found.
    """
    ap_hints = _read_autopilot_port_hints()
    # dbounce records its wire port in the ``port`` field.  Probe
    # autopilot hints first; default wire + mgmt ports as fallback.
    dbounce_ports: list[int] = list(
        dict.fromkeys(
            ap_hints.get("dbounce", [])
            + [DBOUNCE_DEFAULT_WIRE_PORT, DBOUNCE_DEFAULT_MGMT_PORT]
        )
    )
    wire_port = DBOUNCE_DEFAULT_WIRE_PORT
    mgmt_port = DBOUNCE_DEFAULT_MGMT_PORT
    running = any(_loopback_port_open(_p) for _p in dbounce_ports)
    block: dict[str, Any] = {
        "running": running,
        "port": wire_port,
        "mgmt_port": mgmt_port,
        "default_port": DBOUNCE_DEFAULT_WIRE_PORT,
        "default_mgmt_port": DBOUNCE_DEFAULT_MGMT_PORT,
        "mode": "unknown",
        "active_profile": "unknown",
    }
    pghost = os.environ.get(DBOUNCE_ENV_PGHOST, "").strip()
    pgport_raw = os.environ.get(DBOUNCE_ENV_PGPORT, "").strip()
    block["env_var_pointing_here"] = None
    block["misconfig"] = None
    if pghost in _LOOPBACK_HOSTS:
        try:
            pgport = int(pgport_raw) if pgport_raw else 5432
        except ValueError:
            pgport = 5432
        if _loopback_port_open(pgport):
            block["env_var_pointing_here"] = (
                f"{DBOUNCE_ENV_PGHOST}={pghost} "
                f"{DBOUNCE_ENV_PGPORT}={pgport}"
            )
            block["running"] = True
            block["port"] = pgport
        else:
            block["misconfig"] = (
                f"{DBOUNCE_ENV_PGHOST}={pghost} "
                f"{DBOUNCE_ENV_PGPORT}={pgport} but nothing is "
                "listening on that loopback port"
            )
    return block


def detect_gbounce() -> dict[str, Any]:
    """Detect gbounce via HTTP_PROXY / HTTPS_PROXY + loopback probe
    to the management port (since /healthz lives there).

    #514 — canary-port support: autopilot-hinted ports are probed
    alongside the default so non-default gbounce wire/mgmt deployments
    are found.
    """
    ap_hints = _read_autopilot_port_hints()
    gbounce_ports: list[int] = list(
        dict.fromkeys(
            ap_hints.get("gbounce", [])
            + [GBOUNCE_DEFAULT_WIRE_PORT, GBOUNCE_DEFAULT_MGMT_PORT]
        )
    )
    wire_port = GBOUNCE_DEFAULT_WIRE_PORT
    mgmt_port = GBOUNCE_DEFAULT_MGMT_PORT
    running = any(_loopback_port_open(_p) for _p in gbounce_ports)
    block: dict[str, Any] = {
        "running": running,
        "port": wire_port,
        "mgmt_port": mgmt_port,
        "default_port": GBOUNCE_DEFAULT_WIRE_PORT,
        "default_mgmt_port": GBOUNCE_DEFAULT_MGMT_PORT,
        "mode": "unknown",
        "active_profile": "unknown",
    }
    block["env_var_pointing_here"] = None
    block["misconfig"] = None
    for env_name in (GBOUNCE_ENV_HTTP_PROXY, GBOUNCE_ENV_HTTPS_PROXY):
        val = os.environ.get(env_name, "").strip()
        if not val:
            continue
        port_from_env = _parse_url_for_loopback_port(val)
        if port_from_env is None:
            block["env_var_set_elsewhere"] = (
                f"{env_name}={val} (not loopback)"
            )
            continue
        if _loopback_port_open(port_from_env):
            block["env_var_pointing_here"] = (
                f"{env_name}={val}"
            )
            block["running"] = True
            block["port"] = port_from_env
            break
        block["misconfig"] = (
            f"{env_name}={val} but nothing is listening on that port"
        )
    return block


def detect_all_bouncers() -> dict[str, Any]:
    """Run every per-bouncer detector. Returned dict matches the
    ``bouncers`` block of the §A42 posture schema."""
    return {
        "ibounce": detect_ibounce(),
        "kbounce": detect_kbounce(),
        "dbounce": detect_dbounce(),
        "gbounce": detect_gbounce(),
    }
