"""Bouncer process discovery + env-var wiring for `iam-jit posture`.

Detects:
  * Whether each of ibounce / kbounce / dbounce / gbounce is running
    (cheap loopback TCP probe to the bouncer's default management
    port; honors per-bouncer env-var overrides).
  * Whether the operator's env vars point at THAT bouncer (or at a
    different port — the "misconfig" case per
    [[ibounce-honest-positioning]]).
  * For ibounce only: the live active mode + profile name (read
    in-process via the existing helpers when this module is imported
    inside the ibounce mcp/cli process; otherwise reports
    "unknown — bouncer not introspectable from this process").

Each bouncer's default port + env-var name comes from the bouncer's
own CLI/run-command spec:

  * ibounce:  --port 8767 (loopback), env IAM_JIT_BOUNCER_PROFILE
              (env points at 127.0.0.1:8767 via AWS_ENDPOINT_URL)
  * kbounce:  --port 8766, KUBECONFIG points at a kbounce-generated
              file (file header contains a comment marker we scan for)
  * dbounce:  --port 5433 (wire), --mgmt-port 8768. ``posture`` probes
              the mgmt port for /healthz.
  * gbounce:  --port 8080 (wire), --mgmt-port 8769. ``posture`` probes
              the mgmt port (since /healthz lives there per
              [[ibounce-honest-positioning]]).

Process discovery is intentionally NETWORK-PROBE-BASED rather than
``ps``-based — works in containers, doesn't need /proc, doesn't race
with start-up. Cost is one TCP-connect per bouncer per call (< 5ms
total on loopback).
"""

from __future__ import annotations

import os
import re
import socket
from contextlib import closing
from typing import Any

# ---- Default ports + env-var names per bouncer --------------------------
# Source of truth: each bouncer's `run` CLI flag default. If those
# change, update here. Tests pin the defaults (`test_posture_defaults`).

IBOUNCE_DEFAULT_PORT = 8767
IBOUNCE_AWS_ENDPOINT_ENV = "AWS_ENDPOINT_URL"

KBOUNCE_DEFAULT_PORT = 8766
KBOUNCE_ENV_KUBECONFIG = "KUBECONFIG"
# Marker we expect to see at the top of kbounce-generated kubeconfigs.
# kbounce writes ``# Generated by kbounce`` as the first comment.
KBOUNCE_KUBECONFIG_MARKER = "# Generated by kbounce"

DBOUNCE_DEFAULT_WIRE_PORT = 5433
DBOUNCE_DEFAULT_MGMT_PORT = 8768
DBOUNCE_ENV_PGHOST = "PGHOST"
DBOUNCE_ENV_PGPORT = "PGPORT"

GBOUNCE_DEFAULT_WIRE_PORT = 8080
GBOUNCE_DEFAULT_MGMT_PORT = 8769
GBOUNCE_ENV_HTTP_PROXY = "HTTP_PROXY"
GBOUNCE_ENV_HTTPS_PROXY = "HTTPS_PROXY"


# ---- Helpers ------------------------------------------------------------


def _loopback_port_open(port: int, host: str = "127.0.0.1", timeout: float = 0.25) -> bool:
    """Cheap loopback TCP probe. Returns True iff something is
    accepting connections at ``host:port`` within ``timeout`` seconds.

    Never raises — connection failures (refused / unreachable /
    timeout / DNS) all return False. Caller decides what to make of
    a False (could be "not running" OR could be "running on a
    different port").
    """
    if port <= 0 or port > 65535:
        return False
    with closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as sock:
        sock.settimeout(timeout)
        try:
            sock.connect((host, port))
        except OSError:
            return False
        return True


_LOOPBACK_HOSTS = {"127.0.0.1", "localhost", "::1", "[::1]"}


def _parse_url_for_loopback_port(url: str) -> int | None:
    """If ``url`` is a loopback http(s) URL, return its port. Else None.

    Used for AWS_ENDPOINT_URL / HTTP_PROXY decoding. Doesn't validate
    the scheme strictly — anything of shape
    ``[scheme://]host[:port][/...]`` works.
    """
    if not url:
        return None
    s = url.strip()
    # Strip optional scheme.
    if "://" in s:
        s = s.split("://", 1)[1]
    # Strip optional path.
    s = s.split("/", 1)[0]
    # Strip credentials prefix (user:pass@host).
    if "@" in s:
        s = s.split("@", 1)[1]
    # Split host:port — handle IPv6 [::1]:port.
    if s.startswith("["):
        # IPv6 form.
        if "]" not in s:
            return None
        host, _, rest = s.partition("]")
        host = host + "]"
        if rest.startswith(":"):
            port_str = rest[1:]
        else:
            port_str = ""
    else:
        host, _, port_str = s.partition(":")
    if host not in _LOOPBACK_HOSTS:
        return None
    if not port_str:
        # No explicit port; loopback URLs without a port aren't
        # meaningful for bouncer detection (bouncers always bind to
        # an explicit port).
        return None
    try:
        return int(port_str)
    except ValueError:
        return None


def _kubeconfig_is_kbounce(path: str) -> bool:
    """Read the first ~1KB of a kubeconfig + check for the kbounce
    marker. Tolerant of missing file / permission errors / binary
    content — all return False."""
    if not path:
        return False
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            head = fh.read(1024)
    except (OSError, UnicodeDecodeError):
        return False
    return KBOUNCE_KUBECONFIG_MARKER in head


# ---- Per-bouncer detection ---------------------------------------------


def detect_ibounce() -> dict[str, Any]:
    """Detect ibounce's posture.

    Returns a dict matching the §A42 spec's per-bouncer block:
      {
        "running": bool,
        "port": int,
        "default_port": int,
        "mode": str | "unknown",
        "active_profile": str | "unknown",
        "env_var_pointing_here": str | None,
        "misconfig": str | None,
      }

    Live mode / profile read is attempted via the in-process
    ``resolve_active_mode`` / ``resolve_active_profile`` helpers when
    they're importable (i.e. when posture is invoked inside the
    iam-jit Python venv). Failure to import is non-fatal — fields
    fall back to "unknown".
    """
    port = IBOUNCE_DEFAULT_PORT
    running = _loopback_port_open(port)
    block: dict[str, Any] = {
        "running": running,
        "port": port,
        "default_port": IBOUNCE_DEFAULT_PORT,
    }

    # In-process introspection: import the same helpers the MCP tools
    # use. Cheap (no IO beyond reading env vars + YAML).
    mode_info: dict[str, Any] | None = None
    profile_info: dict[str, Any] | None = None
    try:
        from ..bouncer.proxy import resolve_active_mode

        mode_info = resolve_active_mode()
    except Exception:
        mode_info = None
    try:
        from ..bouncer.profiles import load_profiles, resolve_active_profile

        profile = resolve_active_profile(
            cli_flag=None, profiles=load_profiles()
        )
        profile_info = {
            "name": profile.name,
            "deny_keyword_count": len(profile.deny_keywords),
            "deny_verb_count": len(profile.deny_verbs),
            "only_account_id_count": len(profile.only_account_ids),
            "allow_rule_count": len(profile.allow_rules),
            "source": profile.source,
        }
    except Exception:
        profile_info = None

    block["mode"] = mode_info["mode"] if mode_info else "unknown"
    block["mode_source"] = (
        mode_info["source"] if mode_info else "unknown"
    )
    if profile_info:
        block["active_profile"] = profile_info["name"]
        block["profile_summary"] = profile_info
    else:
        block["active_profile"] = "unknown"

    # Env-var wiring + misconfig check.
    endpoint = os.environ.get(IBOUNCE_AWS_ENDPOINT_ENV, "").strip()
    endpoint_port = _parse_url_for_loopback_port(endpoint)
    block["env_var_pointing_here"] = None
    block["misconfig"] = None
    if endpoint:
        if endpoint_port is None:
            # Env points elsewhere (not loopback) — not a misconfig
            # for ibounce, just "operator pointing AWS SDK at a
            # different endpoint".
            block["env_var_pointing_here"] = None
            block["env_var_set_elsewhere"] = (
                f"{IBOUNCE_AWS_ENDPOINT_ENV}={endpoint} "
                "(not loopback)"
            )
        elif endpoint_port == port:
            if running:
                block["env_var_pointing_here"] = (
                    f"{IBOUNCE_AWS_ENDPOINT_ENV}={endpoint}"
                )
            else:
                block["misconfig"] = (
                    f"{IBOUNCE_AWS_ENDPOINT_ENV}={endpoint} but no "
                    "bouncer listening on that port"
                )
        else:
            # Endpoint is loopback but a DIFFERENT port.
            if _loopback_port_open(endpoint_port):
                # Something IS running there — operator probably has
                # ibounce on a non-default port. Not a misconfig.
                block["env_var_pointing_here"] = (
                    f"{IBOUNCE_AWS_ENDPOINT_ENV}={endpoint} "
                    f"(non-default port {endpoint_port})"
                )
                block["running"] = True
                block["port"] = endpoint_port
            else:
                block["misconfig"] = (
                    f"{IBOUNCE_AWS_ENDPOINT_ENV}={endpoint} but no "
                    "bouncer listening on that port"
                )
    return block


def detect_kbounce() -> dict[str, Any]:
    """Detect kbounce's posture. Returns the same shape as
    ``detect_ibounce`` minus the in-process mode/profile (which we
    can't read from a different Python process — Go binary)."""
    port = KBOUNCE_DEFAULT_PORT
    running = _loopback_port_open(port)
    block: dict[str, Any] = {
        "running": running,
        "port": port,
        "default_port": KBOUNCE_DEFAULT_PORT,
        "mode": "unknown",  # Go binary; would need /healthz parse to know
        "active_profile": "unknown",
    }
    kubecfg = os.environ.get(KBOUNCE_ENV_KUBECONFIG, "").strip()
    block["env_var_pointing_here"] = None
    block["misconfig"] = None
    if kubecfg:
        if _kubeconfig_is_kbounce(kubecfg):
            block["env_var_pointing_here"] = (
                f"{KBOUNCE_ENV_KUBECONFIG}={kubecfg} (kbounce-generated)"
            )
            if not running:
                block["misconfig"] = (
                    f"{KBOUNCE_ENV_KUBECONFIG} points at a kbounce-"
                    "generated kubeconfig but kbounce isn't running"
                )
        else:
            block["env_var_set_elsewhere"] = (
                f"{KBOUNCE_ENV_KUBECONFIG}={kubecfg} "
                "(not a kbounce kubeconfig)"
            )
    return block


def detect_dbounce() -> dict[str, Any]:
    """Detect dbounce's posture via PGHOST + PGPORT env vars + a
    loopback probe to the management port."""
    wire_port = DBOUNCE_DEFAULT_WIRE_PORT
    mgmt_port = DBOUNCE_DEFAULT_MGMT_PORT
    running = _loopback_port_open(mgmt_port) or _loopback_port_open(wire_port)
    block: dict[str, Any] = {
        "running": running,
        "port": wire_port,
        "mgmt_port": mgmt_port,
        "default_port": DBOUNCE_DEFAULT_WIRE_PORT,
        "default_mgmt_port": DBOUNCE_DEFAULT_MGMT_PORT,
        "mode": "unknown",
        "active_profile": "unknown",
    }
    pghost = os.environ.get(DBOUNCE_ENV_PGHOST, "").strip()
    pgport_raw = os.environ.get(DBOUNCE_ENV_PGPORT, "").strip()
    block["env_var_pointing_here"] = None
    block["misconfig"] = None
    if pghost in _LOOPBACK_HOSTS:
        try:
            pgport = int(pgport_raw) if pgport_raw else 5432
        except ValueError:
            pgport = 5432
        if _loopback_port_open(pgport):
            block["env_var_pointing_here"] = (
                f"{DBOUNCE_ENV_PGHOST}={pghost} "
                f"{DBOUNCE_ENV_PGPORT}={pgport}"
            )
            block["running"] = True
            block["port"] = pgport
        else:
            block["misconfig"] = (
                f"{DBOUNCE_ENV_PGHOST}={pghost} "
                f"{DBOUNCE_ENV_PGPORT}={pgport} but nothing is "
                "listening on that loopback port"
            )
    return block


def detect_gbounce() -> dict[str, Any]:
    """Detect gbounce via HTTP_PROXY / HTTPS_PROXY + loopback probe
    to the management port (since /healthz lives there)."""
    wire_port = GBOUNCE_DEFAULT_WIRE_PORT
    mgmt_port = GBOUNCE_DEFAULT_MGMT_PORT
    running = _loopback_port_open(mgmt_port) or _loopback_port_open(wire_port)
    block: dict[str, Any] = {
        "running": running,
        "port": wire_port,
        "mgmt_port": mgmt_port,
        "default_port": GBOUNCE_DEFAULT_WIRE_PORT,
        "default_mgmt_port": GBOUNCE_DEFAULT_MGMT_PORT,
        "mode": "unknown",
        "active_profile": "unknown",
    }
    block["env_var_pointing_here"] = None
    block["misconfig"] = None
    for env_name in (GBOUNCE_ENV_HTTP_PROXY, GBOUNCE_ENV_HTTPS_PROXY):
        val = os.environ.get(env_name, "").strip()
        if not val:
            continue
        port_from_env = _parse_url_for_loopback_port(val)
        if port_from_env is None:
            block["env_var_set_elsewhere"] = (
                f"{env_name}={val} (not loopback)"
            )
            continue
        if _loopback_port_open(port_from_env):
            block["env_var_pointing_here"] = (
                f"{env_name}={val}"
            )
            block["running"] = True
            block["port"] = port_from_env
            break
        block["misconfig"] = (
            f"{env_name}={val} but nothing is listening on that port"
        )
    return block


def detect_all_bouncers() -> dict[str, Any]:
    """Run every per-bouncer detector. Returned dict matches the
    ``bouncers`` block of the §A42 posture schema."""
    return {
        "ibounce": detect_ibounce(),
        "kbounce": detect_kbounce(),
        "dbounce": detect_dbounce(),
        "gbounce": detect_gbounce(),
    }
